### ISSUE TITLE
Handle id_ed25519 keys 

### ISSUE THREAD

**Issue by cristianvasquez** [zazuko/barnard59-ftp#16]
When using id_ed25519 keys, the step currently throws:

Cannot parse privateKey: Unsupported key format

**Comment by ludovicm67** [comment]
I did some tests and it seems that barnard59-ftp supports the ED25519 format.
I had a look at the dependencies and `ssh2` supports it.

The issue we faced in that pipeline was that the path to the private key was given instead of the content directly.
An idea is to also add support to file path in addition of the content of the key directly.
I opened an issue #17 to discuss it.

I will let you close this issue, since everything is working well.

**Comment by cristianvasquez** [comment]
yes it supports it, (forgot to close it)
